name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --break-system-packages

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Stop previous runserver (if any)
        run: |
          pkill -f "python manage.py runserver" || true
      
      - name: Start Django server
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 > server.log &
          disown -h %1
