name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --break-system-packages

      - name: Apply migrations
        run: |
          python manage.py migrate

      - name: Restart Gunicorn
        run: |
          sudo systemctl restart gunicorn
